library(chipmine)
library(here)


## This script parse the correlation matrix generated by deeptools to create 
## pairwise correlation table


rm(list = ls())

analysisName <- "pairwise_correlation"

outDir <- here::here("analysis", "correlation_analysis")
outPrefix <- paste(outDir, "/", analysisName, sep = "")

file_pearson <- here("analysis", "correlation_analysis", "An_bigwig_pearson_gene.tab")
file_spearman <- here("analysis", "correlation_analysis", "An_bigwig_spearman_gene.tab")
file_pairs <- here("analysis", "correlation_analysis", "polII_replicates.txt")

##################################################################################

replicates <- readr::read_tsv(file = file_pairs)

## pearson coefficient
pearsonMat <- readr::read_tsv(file = file_pearson, comment = "#", quote = "\'") %>% 
  tibble::column_to_rownames(var = "X1") %>% 
  as.matrix()

# pearsonMat[lower.tri(pearsonMat, diag=TRUE)] <- NA

pearsonDf <- na.omit(as.data.frame(as.table(pearsonMat))) %>% 
  dplyr::mutate(
    Var1 = gsub(pattern = "_normalized.bw", replacement = "", x = Var1),
    Var2 = gsub(pattern = "_normalized.bw", replacement = "", x = Var2)
  ) %>% 
  dplyr::rename(pearson = Freq)


# pearsonDf <- pearsonDf %>% 
#   dplyr::mutate(
#     var1An = gsub(pattern = "^([^_]+)_.*", replacement = "\\1", x = Var1, perl = TRUE),
#     var2An = gsub(pattern = "^([^_]+)_.*", replacement = "\\1", x = Var2, perl = TRUE)
#   ) %>%
#   dplyr::filter(var1An == var2An, Var1 != Var2) %>%
#   dplyr::arrange(Var1, Var2)
# 
# readr::write_tsv(x = pearsonDf, path = paste(outPrefix, ".temp.pairs.tab", sep = ""))


## spearman coefficient
spearmanMat <- readr::read_tsv(file = file_spearman, comment = "#", quote = "\'") %>% 
  tibble::column_to_rownames(var = "X1") %>% 
  as.matrix()

spearmanDf <- na.omit(as.data.frame(as.table(spearmanMat))) %>% 
  dplyr::mutate(
    Var1 = gsub(pattern = "_normalized.bw", replacement = "", x = Var1),
    Var2 = gsub(pattern = "_normalized.bw", replacement = "", x = Var2)
  ) %>% 
  dplyr::rename(spearman = Freq)


replicateCorr <- replicates %>% 
  dplyr::left_join(y = pearsonDf, by = c("rep1" = "Var1", "rep2" = "Var2")) %>% 
  dplyr::left_join(y = spearmanDf, by = c("rep1" = "Var1", "rep2" = "Var2"))

readr::write_tsv(x = replicateCorr, path = paste(outPrefix, ".polII.tab", sep = ""))







