library(chipmine)
library(here)


## This script parse the correlation matrix generated by deeptools to create 
## pairwise correlation table


rm(list = ls())

analysisName <- "pairwise_correlation"

outDir <- here::here("analysis", "correlation_analysis")
path_data <- here::here("analysis", "correlation_analysis")
outPrefix <- paste(outDir, "/", analysisName, sep = "")

file_data <- here("analysis", "correlation_analysis", "corr_file_data.txt")
file_pairs <- here("analysis", "correlation_analysis", "tf_replicates.txt")



##################################################################################

replicates <- readr::read_tsv(file = file_pairs)

corrMatData <- readr::read_tsv(file = file_data)

##################################################################################
i <- 3

for (i in 1:nrow(corrMatData)) {
  ## pearson coefficient
  pearsonMat <- readr::read_tsv(file = paste(path_data, corrMatData$pearson[i], sep = "/"),
                                comment = "#", quote = "\'") %>% 
    tibble::column_to_rownames(var = "X1") %>% 
    as.matrix()
  
  # pearsonMat[lower.tri(pearsonMat, diag=TRUE)] <- NA
  pearsonColName <- paste("pearson", corrMatData$region[i], sep = ".")
  
  pearsonDf <- na.omit(as.data.frame(as.table(pearsonMat))) %>% 
    dplyr::mutate(
      Var1 = gsub(pattern = "_normalized.bw", replacement = "", x = Var1),
      Var2 = gsub(pattern = "_normalized.bw", replacement = "", x = Var2)
    ) %>% 
    dplyr::rename(!!pearsonColName := Freq)
  
  
  ## spearman coefficient
  spearmanMat <- readr::read_tsv(file = paste(path_data, corrMatData$spearman[i], sep = "/"),
                                 comment = "#", quote = "\'") %>% 
    tibble::column_to_rownames(var = "X1") %>% 
    as.matrix()
  
  spearmanColName <- paste("spearman", corrMatData$region[i], sep = ".")
  
  spearmanDf <- na.omit(as.data.frame(as.table(spearmanMat))) %>% 
    dplyr::mutate(
      Var1 = gsub(pattern = "_normalized.bw", replacement = "", x = Var1),
      Var2 = gsub(pattern = "_normalized.bw", replacement = "", x = Var2)
    ) %>% 
    dplyr::rename(!!spearmanColName := Freq)
  
  
  replicates <- replicates %>% 
    dplyr::left_join(y = pearsonDf, by = c("rep1" = "Var1", "rep2" = "Var2")) %>% 
    dplyr::left_join(y = spearmanDf, by = c("rep1" = "Var1", "rep2" = "Var2"))
  
  
}

readr::write_tsv(x = replicates, path = paste(outPrefix, ".TF.tab", sep = ""))

