library(dplyr)
library(data.table)

rm(list = ls())


path = "E:/Chris_UM/Analysis/23_Shuhui_SM_OE_project/correlation_analysis"
setwd(path)


dt = data.table::fread(file = "sample_details.tab", sep = "\t", header = T, stringsAsFactors = F, select = c("strain", "condition", "TimePoint", "IP_tag", "Rep", "NewSampleName", "DataPath"), data.table = T) %>% 
  dplyr::mutate(
    sample = paste(strain, TimePoint, IP_tag, sep = "_"),
    bwFile = paste(DataPath, "/", NewSampleName, "_normalized.bw", sep = "")
    ) %>% 
  data.table::as.data.table()



repDt = data.table::dcast(data = dt,
                          formula = TimePoint + IP_tag + sample ~ Rep,
                          value.var = c("NewSampleName", "bwFile")) %>% 
  dplyr::mutate(command = paste("bigWigCorrelate", bwFile_1, bwFile_2, sep = " ")) %>% 
  dplyr::rename(rep1 = "NewSampleName_1",
                rep2 = "NewSampleName_2")



#' Parse deeptools bigwig correlation matrix
#'
#' @param matFile correlation matrix file generated by deeptools' plotCorrelation tool
#' @param corrColName column name to be used for correlation column
#'
#' @return a dataframe with pairwise correlation information
#' @export
#'
#' @examples NA
parse_deeptools_corr_mat = function(matFile, corrColName){
 
  ## read the deeptools correlation matrix file
  deeptoolsAll = data.table::fread(file = matFile, sep = "\t", header = T, stringsAsFactors = F) %>%
    dplyr::rename(sampleId_1 = "V1") %>% 
    data.table::as.data.table()
  
  ## reshape the matrix to pairwise correlation table
  pairwiseCorr = data.table::melt(data = deeptoolsAll, id.vars = c("sampleId_1"), variable.name = "sampleId_2", value.name = corrColName) %>%
    dplyr::mutate(
      sampleId_1 = gsub(pattern = "^'(.*)_normalized.bw'", replacement = "\\1", x = sampleId_1),
      sampleId_2 = gsub(pattern = "^'(.*)_normalized.bw'", replacement = "\\1", x = sampleId_2))
  
  return(pairwiseCorr)
}


## A. nidulans pearson correlation
geneCorr = parse_deeptools_corr_mat(matFile = "An_bigwig_pearson_gene.tab", corrColName = "genebody_correlation")
promoterCorr = parse_deeptools_corr_mat(matFile = "An_bigwig_pearson_promoter.tab", corrColName = "promoter_correlation")
binCorr = parse_deeptools_corr_mat(matFile = "An_bigwig_pearson_bin.tab", corrColName = "binwise_correlation")




pairwiseCorrMat = repDt %>% 
  dplyr::left_join(y = binCorr, by = c("rep1" = "sampleId_1", "rep2" = "sampleId_2")) %>% 
  dplyr::left_join(y = geneCorr, by = c("rep1" = "sampleId_1", "rep2" = "sampleId_2")) %>%
  dplyr::left_join(y = promoterCorr, by = c("rep1" = "sampleId_1", "rep2" = "sampleId_2"))




data.table::fwrite(x = pairwiseCorrMat, file = "corr_commands.tab", sep = "\t", na = "NA", quote = F, col.names = T)



















